In [1]:
import numpy as np
import pandas as pd
import datetime

import seaborn as sns
import ipywidgets as widgets
import matplotlib.pyplot as plt

%matplotlib widget
%matplotlib inline

In [2]:
data = pd.read_csv("../Data Collection/final_data.csv", sep=',', lineterminator='\n')
data.head()

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,listed_count,created_at,favourites_count,geo_enabled,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",NaN,False,1698,4,53,2016-10-15 21:32:11,4,False,False,13097,NaN,False,False,False
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,https://t.co/DJ4TYZgm7Q,False,823,852,5,2016-11-09 05:01:30,516,False,False,251,NaN,False,False,False
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",https://t.co/jIrurMaqEX,False,193,805,2,2017-06-17 05:34:27,4105,True,False,1201,NaN,False,False,False
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,NaN,False,569,659,2,2016-07-21 13:32:25,10086,True,False,1648,NaN,True,True,False
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",NaN,False,748235,118,1818,2012-01-15 16:32:35,152,True,True,4292,NaN,True,False,False

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36590 entries, 0 to 36589
Data columns (total 20 columns):
Unnamed: 0                      36590 non-null int64
is_bot                          36590 non-null int64
id                              36590 non-null int64
screen_name                     36590 non-null object
location                        23826 non-null object
description                     29471 non-null object
url                             15065 non-null object
protected                       36590 non-null bool
followers_count                 36590 non-null int64
friends_count                   36590 non-null int64
listed_count                    36590 non-null int64
created_at                      36590 non-null object
favourites_count                36590 non-null int64
geo_enabled                     36590 non-null bool
verified                        36590 non-null bool
statuses_count                  36590 non-null int64
lang                            0 non-null float64
profile_use_background_image    36590 non-null bool
default_profile                 36590 non-null bool
default_profile_image           36590 non-null bool
dtypes: bool(6), float64(1), int64(8), object(5)
memory usage: 4.1+ MB

In [4]:
data.describe(include='all')

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,listed_count,created_at,favourites_count,geo_enabled,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image
count,36590.000000,36590.000000,3.659000e+04,36590,23826,29471,15065,36590,3.659000e+04,3.659000e+04,3.659000e+04,36590,36590.000000,36590,36590,3.659000e+04,0.0,36590,36590,36590
unique,NaN,NaN,NaN,36590,11719,29217,14984,2,NaN,NaN,NaN,36582,NaN,2,2,NaN,NaN,2,2,2
top,NaN,NaN,NaN,ifiorentino,"Los Angeles, CA",.,https://t.co/ScNVY5d91C,False,NaN,NaN,NaN,2015-11-03 09:18:18,NaN,False,False,NaN,NaN,True,False,False
freq,NaN,NaN,NaN,1,507,18,15,35156,NaN,NaN,NaN,2,NaN,19739,29171,NaN,NaN,30917,21276,36042
mean,18294.500000,0.357967,1.209874e+17,NaN,NaN,NaN,NaN,NaN,3.836379e+05,4.297925e+03,9.329094e+02,NaN,13722.288904,NaN,NaN,2.199612e+04,NaN,NaN,NaN,NaN
std,10562.767511,0.479409,2.991924e+17,NaN,NaN,NaN,NaN,NaN,2.535999e+06,4.849551e+04,1.718303e+04,NaN,38121.756078,NaN,NaN,7.050774e+04,NaN,NaN,NaN,NaN
min,0.000000,0.000000,4.180000e+02,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN
25%,9147.250000,0.000000,9.762581e+07,NaN,NaN,NaN,NaN,NaN,3.500000e+01,3.600000e+01,0.000000e+00,NaN,373.250000,NaN,NaN,1.360000e+03,NaN,NaN,NaN,NaN
50%,18294.500000,0.000000,3.937624e+08,NaN,NaN,NaN,NaN,NaN,3.700000e+02,2.990000e+02,4.000000e+00,NaN,2115.000000,NaN,NaN,4.368000e+03,NaN,NaN,NaN,NaN
75%,27441.750000,1.000000,2.438237e+09,NaN,NaN,NaN,NaN,NaN,9.237000e+03,9.140000e+02,1.210000e+02,NaN,9940.000000,NaN,NaN,1.782375e+04,NaN,NaN,NaN,NaN
max,36589.000000,1.000000,1.120974e+18,NaN,NaN,NaN,NaN,NaN,1.303105e+08,4.228360e+06,3.112202e+06,NaN,970422.000000,NaN,NaN,2.774232e+06,NaN,NaN,NaN,NaN

In [5]:
data.isnull().sum()

Unnamed: 0                          0
is_bot                              0
id                                  0
screen_name                         0
location                        12764
description                      7119
url                             21525
protected                           0
followers_count                     0
friends_count                       0
listed_count                        0
created_at                          0
favourites_count                    0
geo_enabled                         0
verified                            0
statuses_count                      0
lang                            36590
profile_use_background_image        0
default_profile                     0
default_profile_image               0
dtype: int64

In [6]:
# convert boolean data to integers

data["protected"] = data["protected"].astype(int)
data["geo_enabled"] = data["geo_enabled"].astype(int)
data["verified"] = data["verified"].astype(int)
data["profile_use_background_image"] = data["profile_use_background_image"].astype(int)
data["default_profile"] = data["default_profile"].astype(int)
data["default_profile_image"] = data["default_profile_image"].astype(int)

for i in data.index:
  if data["url"][i] is None:
    data["url"][i] = 0
  else:
    data["url"][i] = 1


data.head()

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,listed_count,created_at,favourites_count,geo_enabled,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,53,2016-10-15 21:32:11,4,0,0,13097,NaN,0,0,0
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,1,0,823,852,5,2016-11-09 05:01:30,516,0,0,251,NaN,0,0,0
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",1,0,193,805,2,2017-06-17 05:34:27,4105,1,0,1201,NaN,0,0,0
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,2,2016-07-21 13:32:25,10086,1,0,1648,NaN,1,1,0
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,1818,2012-01-15 16:32:35,152,1,1,4292,NaN,1,0,0

In [7]:
data.shape

(36590, 20)

In [8]:
# create a new feature to see how many days the account has been in use

today = datetime.datetime.now()
today = pd.to_datetime(today)

In [9]:
for i in data.index:
     data['created_at'][i] = pd.to_datetime(data['created_at'][i])

type(data['created_at'][0])

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

pandas._libs.tslibs.timestamps.Timestamp

In [10]:
account_age = []
for i in data.index:
    account_age.append((today - data['created_at'][i]).days)

data['account_age'] = account_age

In [11]:
result = data.select_dtypes(include='number')
result.columns

Index(['Unnamed: 0', 'is_bot', 'id', 'protected', 'followers_count',
       'friends_count', 'listed_count', 'favourites_count', 'geo_enabled',
       'verified', 'statuses_count', 'lang', 'profile_use_background_image',
       'default_profile', 'default_profile_image', 'account_age'],
      dtype='object')

In [12]:
plt.rcParams["figure.figsize"] = (15,8)
def plot_distribution(feature_to_use):
    sns.distplot(data[feature_to_use], hist=True, kde=False, 
             bins=int(180/5), color = 'blue',
             hist_kws={'edgecolor':'black'})

    # minimun = data[feature_to_use].min()
    # maximum = data[feature_to_use].max()

    # plt.xlim(0, maximum)

    # plt.hist(data[feature_to_use], color = 'blue', edgecolor = 'black',
    #      bins = int(180/5))
     

numeric_columns = ['followers_count',
       'friends_count', 'listed_count', 'favourites_count',
       'statuses_count', 'lang', 'account_age',
       'avg_daily_followers', 'avg_daily_friends', 'avg_daily_favorites',
       'friends_log', 'followers_log', 'favs_log']

widgets.interact(plot_distribution, feature_to_use=numeric_columns);

interactive(children=(Dropdown(description='feature_to_use', options=('followers_count', 'friends_count', 'lis‚Ä¶

Looking at the distribution of the values for the plots above, we see that the values are skewed.
I will set up some transformation parameters to try and correct the skewed features.

In [13]:
log_follower_growth_rate = []
for i in data.index:
    log_follower_growth_rate.append(data['followers_count'][i] / data['account_age'][i])

data['log_follower_growth_rate'] = log_follower_growth_rate
data.head()

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,...,favourites_count,geo_enabled,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,...,4,0,0,13097,NaN,0,0,0,2032,0.835630
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,1,0,823,852,...,516,0,0,251,NaN,0,0,0,2007,0.410065
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",1,0,193,805,...,4105,1,0,1201,NaN,0,0,0,1787,0.108002
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,...,10086,1,0,1648,NaN,1,1,0,2118,0.268650
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,...,152,1,1,4292,NaN,1,0,0,3767,198.628882

In [14]:
log_friends_growth_rate = []
for i in data.index:
    log_friends_growth_rate.append(data['friends_count'][i] / data['account_age'][i])

data['log_friends_growth_rate'] = log_friends_growth_rate
data.head()

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,...,geo_enabled,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate,log_friends_growth_rate
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,...,0,0,13097,NaN,0,0,0,2032,0.835630,0.001969
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,1,0,823,852,...,0,0,251,NaN,0,0,0,2007,0.410065,0.424514
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",1,0,193,805,...,1,0,1201,NaN,0,0,0,1787,0.108002,0.450476
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,...,1,0,1648,NaN,1,1,0,2118,0.268650,0.311143
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,...,1,1,4292,NaN,1,0,0,3767,198.628882,0.031325

In [15]:
popularity = []
for i in data.index:
  popularity.append(data['followers_count'][i] / (data['followers_count'][i] + data['friends_count'][i]))

data['popularity'] = popularity
data.head()

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in longlong_scalars
  This is separate from the ipykernel package so we can avoid doing imports until

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,...,verified,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,...,0,13097,NaN,0,0,0,2032,0.835630,0.001969,0.997650
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,1,0,823,852,...,0,251,NaN,0,0,0,2007,0.410065,0.424514,0.491343
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",1,0,193,805,...,0,1201,NaN,0,0,0,1787,0.108002,0.450476,0.193387
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,...,0,1648,NaN,1,1,0,2118,0.268650,0.311143,0.463355
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,...,1,4292,NaN,1,0,0,3767,198.628882,0.031325,0.999842

In [16]:
log_friends_follower_ratio = []
for i in data.index:
    log_friends_follower_ratio.append( data['friends_count'][i] / data['followers_count'][i])

data['log_friends_follower_ratio'] = log_friends_follower_ratio
data.head()

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in longlong_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in longlong_scalars
  This is separate from the ipykernel package so we can avoid doing imports until

,Unnamed: 0,is_bot,id,screen_name,location,description,url,protected,followers_count,friends_count,...,statuses_count,lang,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio
0,0,1,787405734442958848,best_in_dumbest,NaN,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,...,13097,NaN,0,0,0,2032,0.835630,0.001969,0.997650,0.002356
1,1,0,796216118331310080,CJRubinPhoto,United States,Photographing the American West since 1980. I ...,1,0,823,852,...,251,NaN,0,0,0,2007,0.410065,0.424514,0.491343,1.035237
2,2,1,875949740503859200,SVGEGENT,NaN,"Part savage, all gentleman üßê\n ...",1,0,193,805,...,1201,NaN,0,0,0,1787,0.108002,0.450476,0.193387,4.170984
3,3,1,756119643622735872,TinkerVHELPK5,"Birmingham, AL",Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,...,1648,NaN,1,1,0,2118,0.268650,0.311143,0.463355,1.158172
4,4,0,464781334,JoleonLescott,"England, United Kingdom","Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,...,4292,NaN,1,0,0,3767,198.628882,0.031325,0.999842,0.000158

In [17]:
logs_data = data

# remove some columns
logs_data.drop(['Unnamed: 0', 'id', 'screen_name', 'location', 'created_at', 'lang'], axis=1, inplace=True)
logs_data.head()

,is_bot,description,url,protected,followers_count,friends_count,listed_count,favourites_count,geo_enabled,verified,statuses_count,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio
0,1,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,53,4,0,0,13097,0,0,0,2032,0.835630,0.001969,0.997650,0.002356
1,0,Photographing the American West since 1980. I ...,1,0,823,852,5,516,0,0,251,0,0,0,2007,0.410065,0.424514,0.491343,1.035237
2,1,"Part savage, all gentleman üßê\n ...",1,0,193,805,2,4105,1,0,1201,0,0,0,1787,0.108002,0.450476,0.193387,4.170984
3,1,Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,2,10086,1,0,1648,1,1,0,2118,0.268650,0.311143,0.463355,1.158172
4,0,"Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,1818,152,1,1,4292,1,0,0,3767,198.628882,0.031325,0.999842,0.000158

In [18]:
logs_data.rename(columns = {'followers_count' : 'log_followers_count', 'friends_count' : 'log_friends_count', 'listed_count' : 'log_listed_count', 'favourites_count' : 'log_favourites_count', 'statuses_count' : 'log_statuses_count'}, inplace = True)

logs_data.head()

,is_bot,description,url,protected,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,geo_enabled,verified,log_statuses_count,profile_use_background_image,default_profile,default_profile_image,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio
0,1,"Blame @xaiax, Inspired by @MakingInvisible, us...",1,0,1698,4,53,4,0,0,13097,0,0,0,2032,0.835630,0.001969,0.997650,0.002356
1,0,Photographing the American West since 1980. I ...,1,0,823,852,5,516,0,0,251,0,0,0,2007,0.410065,0.424514,0.491343,1.035237
2,1,"Part savage, all gentleman üßê\n ...",1,0,193,805,2,4105,1,0,1201,0,0,0,1787,0.108002,0.450476,0.193387,4.170984
3,1,Wife.Godmother.Friend.Feline Fanatic! Assistan...,1,0,569,659,2,10086,1,0,1648,1,1,0,2118,0.268650,0.311143,0.463355,1.158172
4,0,"Loans Manager @mancity, @pumafootball Ambassad...",1,0,748235,118,1818,152,1,1,4292,1,0,0,3767,198.628882,0.031325,0.999842,0.000158

In [19]:
# remove some other columns

logs_data.drop(['url', 'geo_enabled', 'profile_use_background_image', 'default_profile_image'], axis=1, inplace=True)

data.head()

,is_bot,description,protected,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,verified,log_statuses_count,default_profile,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio
0,1,"Blame @xaiax, Inspired by @MakingInvisible, us...",0,1698,4,53,4,0,13097,0,2032,0.835630,0.001969,0.997650,0.002356
1,0,Photographing the American West since 1980. I ...,0,823,852,5,516,0,251,0,2007,0.410065,0.424514,0.491343,1.035237
2,1,"Part savage, all gentleman üßê\n ...",0,193,805,2,4105,0,1201,0,1787,0.108002,0.450476,0.193387,4.170984
3,1,Wife.Godmother.Friend.Feline Fanatic! Assistan...,0,569,659,2,10086,0,1648,1,2118,0.268650,0.311143,0.463355,1.158172
4,0,"Loans Manager @mancity, @pumafootball Ambassad...",0,748235,118,1818,152,1,4292,0,3767,198.628882,0.031325,0.999842,0.000158

In [20]:
logs_data.dtypes

is_bot                          int64
description                    object
protected                       int32
log_followers_count             int64
log_friends_count               int64
log_listed_count                int64
log_favourites_count            int64
verified                        int32
log_statuses_count              int64
default_profile                 int32
account_age                     int64
log_follower_growth_rate      float64
log_friends_growth_rate       float64
popularity                    float64
log_friends_follower_ratio    float64
dtype: object

In [22]:
# cast columns to appropriate datatypes

logs_data['log_followers_count'] = logs_data['log_followers_count'].astype(np.float64)
logs_data['log_friends_count'] = logs_data['log_friends_count'].astype(np.float64)
logs_data['log_listed_count'] = logs_data['log_listed_count'].astype(np.float64)
logs_data['log_favourites_count'] = logs_data['log_favourites_count'].astype(np.float64)
logs_data['log_statuses_count'] = logs_data['log_statuses_count'].astype(np.float64)
logs_data['description'] = logs_data['description'].astype(str).str.replace('/',' ')

descript = []
for i in logs_data.index:
  descript.append(logs_data['description'][i])

logs_data['descript'] = descript
del logs_data['description']

In [23]:
for i in logs_data.index:
  if logs_data['log_followers_count'][i] == 0:
    logs_data['log_followers_count'][i] = -1
  else:
    logs_data['log_followers_count'][i] =  np.log(logs_data['log_followers_count'][i])

  if logs_data['log_friends_count'][i] == 0:
    logs_data['log_friends_count'][i] = -1
  else:
    logs_data['log_friends_count'][i] =  np.log(logs_data['log_friends_count'][i])

  if logs_data['log_listed_count'][i] == 0:
    logs_data['log_listed_count'][i] = -1
  else:
    logs_data['log_listed_count'][i] =  np.log(logs_data['log_listed_count'][i])

  if logs_data['log_favourites_count'][i] == 0:
    logs_data['log_favourites_count'][i] = -1
  else:
    logs_data['log_favourites_count'][i] =  np.log(logs_data['log_favourites_count'][i])

  if logs_data['log_statuses_count'][i] == 0:
    logs_data['log_statuses_count'][i] = -1
  else:
    logs_data['log_statuses_count'][i] =  np.log(logs_data['log_statuses_count'][i])

  if logs_data['log_follower_growth_rate'][i] == 0:
    logs_data['log_follower_growth_rate'][i] = -1
  else:
    logs_data['log_follower_growth_rate'][i] =  np.log(logs_data['log_follower_growth_rate'][i])

  if logs_data['log_friends_growth_rate'][i] == 0:
    logs_data['log_friends_growth_rate'][i] = -1
  else:
    logs_data['log_friends_growth_rate'][i] =  np.log(logs_data['log_friends_growth_rate'][i])

  if logs_data['log_friends_follower_ratio'][i] == 0:
    logs_data['log_friends_follower_ratio'][i] = -1
  else:
    logs_data['log_friends_follower_ratio'][i] =  np.log(logs_data['log_friends_follower_ratio'][i])

logs_data.head()

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\oluwanifemi.aweda\Downloads\Nze-FakeAccount\nze\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,is_bot,protected,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,verified,log_statuses_count,default_profile,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,descript
0,1,0,7.437206,1.386294,3.970292,1.386294,0,9.480138,0,2032,-0.179569,-6.230481,0.997650,-6.050912,"Blame @xaiax, Inspired by @MakingInvisible, us..."
1,0,0,6.712956,6.747587,1.609438,6.246107,0,5.525453,0,2007,-0.891440,-0.856810,0.491343,0.034630,Photographing the American West since 1980. I ...
2,1,0,5.262690,6.690842,0.693147,8.319961,0,7.090910,0,1787,-2.225603,-0.797451,0.193387,1.428152,"Part savage, all gentleman üßê\n ..."
3,1,0,6.343880,6.490724,0.693147,9.218904,0,7.407318,1,2118,-1.314347,-1.167504,0.463355,0.146843,Wife.Godmother.Friend.Feline Fanatic! Assistan...
4,0,0,13.525472,4.770685,7.505492,5.023881,1,8.364508,0,3767,5.291438,-3.463350,0.999842,-8.754788,"Loans Manager @mancity, @pumafootball Ambassad..."

In [25]:
bot_score = []
for i in logs_data.index:
  temp = logs_data['log_friends_follower_ratio'][i] + logs_data['log_friends_growth_rate'][i] - logs_data['log_follower_growth_rate'][i] - logs_data['log_listed_count'][i]
  if logs_data['default_profile'][i] == 1:
    temp += 5
  if len(logs_data['descript'][i]) == 0:
    temp += 5
  if logs_data['verified'][i] == 1:
    temp -= 10
  bot_score.append(temp)

logs_data['bot_score'] = bot_score
logs_data.head()

,is_bot,protected,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,verified,log_statuses_count,default_profile,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,descript,bot_score
0,1,0,7.437206,1.386294,3.970292,1.386294,0,9.480138,0,2032,-0.179569,-6.230481,0.997650,-6.050912,"Blame @xaiax, Inspired by @MakingInvisible, us...",-16.072116
1,0,0,6.712956,6.747587,1.609438,6.246107,0,5.525453,0,2007,-0.891440,-0.856810,0.491343,0.034630,Photographing the American West since 1980. I ...,-1.540177
2,1,0,5.262690,6.690842,0.693147,8.319961,0,7.090910,0,1787,-2.225603,-0.797451,0.193387,1.428152,"Part savage, all gentleman üßê\n ...",2.163157
3,1,0,6.343880,6.490724,0.693147,9.218904,0,7.407318,1,2118,-1.314347,-1.167504,0.463355,0.146843,Wife.Godmother.Friend.Feline Fanatic! Assistan...,4.600539
4,0,0,13.525472,4.770685,7.505492,5.023881,1,8.364508,0,3767,5.291438,-3.463350,0.999842,-8.754788,"Loans Manager @mancity, @pumafootball Ambassad...",-35.015068

In [29]:
logs_data.drop(['descript', 'protected', 'verified', 'default_profile'], axis=1, inplace=True)
logs_data.head()

,is_bot,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,log_statuses_count,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,bot_score
0,1,7.437206,1.386294,3.970292,1.386294,9.480138,2032,-0.179569,-6.230481,0.997650,-6.050912,-16.072116
1,0,6.712956,6.747587,1.609438,6.246107,5.525453,2007,-0.891440,-0.856810,0.491343,0.034630,-1.540177
2,1,5.262690,6.690842,0.693147,8.319961,7.090910,1787,-2.225603,-0.797451,0.193387,1.428152,2.163157
3,1,6.343880,6.490724,0.693147,9.218904,7.407318,2118,-1.314347,-1.167504,0.463355,0.146843,4.600539
4,0,13.525472,4.770685,7.505492,5.023881,8.364508,3767,5.291438,-3.463350,0.999842,-8.754788,-35.015068

In [32]:
logs_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36590 entries, 0 to 36589
Data columns (total 12 columns):
is_bot                        36590 non-null int64
log_followers_count           36590 non-null float64
log_friends_count             36590 non-null float64
log_listed_count              36590 non-null float64
log_favourites_count          36590 non-null float64
log_statuses_count            36590 non-null float64
account_age                   36590 non-null int64
log_follower_growth_rate      36590 non-null float64
log_friends_growth_rate       36590 non-null float64
popularity                    35539 non-null float64
log_friends_follower_ratio    35539 non-null float64
bot_score                     35539 non-null float64
dtypes: float64(10), int64(2)
memory usage: 3.4 MB

In [33]:
logs_data.describe()

,is_bot,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,log_statuses_count,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,bot_score
count,36590.000000,36590.000000,36590.000000,36590.000000,36590.000000,36590.000000,36590.000000,36590.000000,36590.000000,35539.000000,3.553900e+04,3.553900e+04
mean,0.357967,6.590782,4.780508,2.337483,7.307641,8.283144,3656.865428,-1.298495,-1.998837,0.637952,inf,inf
std,0.479409,4.210982,3.145663,3.193905,2.716991,2.159465,1012.639455,3.851847,1.730278,0.335980,NaN,NaN
min,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1111.000000,-8.512181,-8.498418,0.000000,-1.675627e+01,-5.440609e+01
25%,0.000000,3.555348,3.583519,-1.000000,5.922248,7.215240,2953.250000,-4.187640,-2.892800,0.340531,-2.039125e+00,-1.199161e+01
50%,0.000000,5.913503,5.700444,1.386294,7.656810,8.382060,3855.500000,-1.938487,-1.757237,0.638235,-5.677130e-01,-5.854076e-02
75%,1.000000,9.130972,6.817831,4.795791,9.204322,9.788287,4525.000000,0.890643,-1.000000,0.999071,6.609282e-01,5.689473e+00
max,1.000000,18.685430,15.257325,14.950841,13.785486,14.835885,5787.000000,10.081294,6.788062,1.000000,inf,inf

In [34]:
logs_data.isnull().sum()

is_bot                           0
log_followers_count              0
log_friends_count                0
log_listed_count                 0
log_favourites_count             0
log_statuses_count               0
account_age                      0
log_follower_growth_rate         0
log_friends_growth_rate          0
popularity                    1051
log_friends_follower_ratio    1051
bot_score                     1051
dtype: int64

In [35]:
logs_data.dropna(inplace=True)

In [36]:
logs_data.isnull().sum()

is_bot                        0
log_followers_count           0
log_friends_count             0
log_listed_count              0
log_favourites_count          0
log_statuses_count            0
account_age                   0
log_follower_growth_rate      0
log_friends_growth_rate       0
popularity                    0
log_friends_follower_ratio    0
bot_score                     0
dtype: int64

In [37]:
# remove positive and negative infinity values
logs_data = logs_data.reset_index()
logs_data.replace([np.inf, -np.inf], np.nan, inplace=True)

data.head()

,is_bot,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,log_statuses_count,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,bot_score
0,1,7.437206,1.386294,3.970292,1.386294,9.480138,2032,-0.179569,-6.230481,0.997650,-6.050912,-16.072116
1,0,6.712956,6.747587,1.609438,6.246107,5.525453,2007,-0.891440,-0.856810,0.491343,0.034630,-1.540177
2,1,5.262690,6.690842,0.693147,8.319961,7.090910,1787,-2.225603,-0.797451,0.193387,1.428152,2.163157
3,1,6.343880,6.490724,0.693147,9.218904,7.407318,2118,-1.314347,-1.167504,0.463355,0.146843,4.600539
4,0,13.525472,4.770685,7.505492,5.023881,8.364508,3767,5.291438,-3.463350,0.999842,-8.754788,-35.015068

In [38]:
logs_data.isnull().sum()

index                           0
is_bot                          0
log_followers_count             0
log_friends_count               0
log_listed_count                0
log_favourites_count            0
log_statuses_count              0
account_age                     0
log_follower_growth_rate        0
log_friends_growth_rate         0
popularity                      0
log_friends_follower_ratio    229
bot_score                     229
dtype: int64

In [40]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(logs_data)

,index,is_bot,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,log_statuses_count,account_age,log_follower_growth_rate,log_friends_growth_rate,popularity,log_friends_follower_ratio,bot_score
0,0.0,1.0,7.437206,1.386294,3.970292,1.386294,9.480138,2032.0,-0.179569,-6.230481,0.997650,-6.050912,-16.072116
1,1.0,0.0,6.712956,6.747587,1.609438,6.246107,5.525453,2007.0,-0.891440,-0.856810,0.491343,0.034630,-1.540177
2,2.0,1.0,5.262690,6.690842,0.693147,8.319961,7.090910,1787.0,-2.225603,-0.797451,0.193387,1.428152,2.163157
3,3.0,1.0,6.343880,6.490724,0.693147,9.218904,7.407318,2118.0,-1.314347,-1.167504,0.463355,0.146843,4.600539
4,4.0,0.0,13.525472,4.770685,7.505492,5.023881,8.364508,3767.0,5.291438,-3.463350,0.999842,-8.754788,-35.015068
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35534,36585.0,0.0,4.976734,7.069023,1.098612,6.602588,6.047372,4657.0,-3.469393,-1.377103,0.109848,2.092290,8.085967
35535,36586.0,0.0,14.015214,6.525030,7.237059,9.234740,10.175421,3411.0,5.880454,-1.609731,0.999442,-7.490185,-32.217428
35536,36587.0,0.0,11.361719,5.236442,5.579730,6.386879,8.750049,3402.0,3.229600,-2.895677,0.997818,-6.125277,-22.830283
35537,36588.0,0.0,4.934474,5.111988,1.098612,6.924612,6.912743,3528.0,-3.234012,-3.056499,0.455738,0.177514,-0.743585
35538,36589.0,1.0,1.609438,3.663562,-1.000000,6.981006,7.336937,3801.0,-6.633582,-4.579458,0.113636,2.054124,5.108247

In [42]:
logs_data.drop(['index', 'log_friends_growth_rate', 'log_friends_follower_ratio', 'bot_score'], axis=1, inplace=True)
logs_data.head()

,is_bot,log_followers_count,log_friends_count,log_listed_count,log_favourites_count,log_statuses_count,account_age,log_follower_growth_rate,popularity
0,1,7.437206,1.386294,3.970292,1.386294,9.480138,2032,-0.179569,0.997650
1,0,6.712956,6.747587,1.609438,6.246107,5.525453,2007,-0.891440,0.491343
2,1,5.262690,6.690842,0.693147,8.319961,7.090910,1787,-2.225603,0.193387
3,1,6.343880,6.490724,0.693147,9.218904,7.407318,2118,-1.314347,0.463355
4,0,13.525472,4.770685,7.505492,5.023881,8.364508,3767,5.291438,0.999842